### PR TITLE
update nugets and code. Tested on real android and iPhone devices

### PR DESCRIPTION
**Pull request by GioviQ**
only in XamarinForms

### CODE REVIEW

**Comment by GioviQ** [comment]
only in XamarinForms

**Comment by leastprivilege** [comment]
Cool. Thank you! Can I add you as a contact, if there are any questions? I don't know anything about Xamarin tbh.

**Comment by GioviQ** [comment]
Of course @leastprivilege

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
