### PR TITLE
Add support for UWP system browser

### PR DESCRIPTION
**Pull request by onovotny**
Very basic sample, no real error or time out handling.

### CODE REVIEW

**Comment by leastprivilege** [comment]
thanks - looks good!

@brockallen Can you have a look - I can't do UWP on my Server VM.

**Comment by onovotny** [comment]
I did notice that CallAPI was crashing; wasn't sure if something changed?

**Comment by leastprivilege** [comment]
The URL has changed

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/041aada16dd9c6985712364c48626b3ad5253e1b/iOS11Client/iOS11Client/ViewController.cs#L104

**Comment by onovotny** [comment]
Fixed in the sample

**Comment by brockallen** [comment]
Is this meant to open in VS2015 or 2017? It naturally wants 2015 and it doesn't work in there, but if I explicitly open it in 2017 it works, builds, and runs fine.

**Comment by onovotny** [comment]
It requires VS 2017, not sure why the version selector isn't doing that for you?

**Comment by onovotny** [comment]
VS didn't do it automatically, but I updated the SLN to specify VS 15.x, so the double-click action should open in the right VS now.

**Comment by onovotny** [comment]
As an aside, the Windows CU and later SDK's require 2017. VS 2015 can only be used up through targeting AU. As far as adoption rates go, AU and lower account for about 12%: http://reports.adduplex.com/reports/2017-12/

**Comment by brockallen** [comment]
Ok. So yea, looks good. Thanks

**Pull request merged**
